# /path/to/config/config.toml
[Node]
DataDir = "/root/.ethereum"

[Network]
Port = 30303
NoDiscover = false

[HTTP]
Enabled = true
Host = "0.0.0.0"
Port = 8545
CorsDomain = "*"
VirtualHosts = "localhost"

[P2P]
ListenAddr = ":30303"
MaxPeers = 50
